/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateOrdersRouteImport } from './routes/_private/orders'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateWishlistRouteImport } from './routes/_private/wishlist'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicCartRouteImport } from './routes/_public/cart'
import { Route as PublicProductsProductIdRouteImport } from './routes/_public/products/$productId'
import { Route as CatalogueProductsSlugRouteImport } from './routes/catalogue/products/$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateOrdersRoute = PrivateOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateWishlistRoute = PrivateWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => PublicRoute,
} as any)
const CatalogueProductsSlugRoute = CatalogueProductsSlugRouteImport.update({
  id: '/catalogue/products/$slug',
  path: '/catalogue/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/orders': typeof PrivateOrdersRoute
  '/profile': typeof PrivateProfileRoute
  '/wishlist': typeof PrivateWishlistRoute
  '/cart': typeof PublicCartRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/catalogue/products/$slug': typeof CatalogueProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/orders': typeof PrivateOrdersRoute
  '/profile': typeof PrivateProfileRoute
  '/wishlist': typeof PrivateWishlistRoute
  '/cart': typeof PublicCartRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/catalogue/products/$slug': typeof CatalogueProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/orders': typeof PrivateOrdersRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/wishlist': typeof PrivateWishlistRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/products/$productId': typeof PublicProductsProductIdRoute
  '/catalogue/products/$slug': typeof CatalogueProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/cart'
    | '/products/$productId'
    | '/catalogue/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/wishlist'
    | '/cart'
    | '/products/$productId'
    | '/catalogue/products/$slug'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_public'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_private/dashboard'
    | '/_private/orders'
    | '/_private/profile'
    | '/_private/wishlist'
    | '/_public/cart'
    | '/_public/'
    | '/_public/products/$productId'
    | '/catalogue/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  CatalogueProductsSlugRoute: typeof CatalogueProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/orders': {
      id: '/_private/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof PrivateOrdersRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/wishlist': {
      id: '/_private/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof PrivateWishlistRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/$productId': {
      id: '/_public/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof PublicProductsProductIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/catalogue/products/$slug': {
      id: '/catalogue/products/$slug'
      path: '/catalogue/products/$slug'
      fullPath: '/catalogue/products/$slug'
      preLoaderRoute: typeof CatalogueProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateOrdersRoute: typeof PrivateOrdersRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateWishlistRoute: typeof PrivateWishlistRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateOrdersRoute: PrivateOrdersRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateWishlistRoute: PrivateWishlistRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicCartRoute: typeof PublicCartRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProductsProductIdRoute: typeof PublicProductsProductIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCartRoute: PublicCartRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  CatalogueProductsSlugRoute: CatalogueProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
